DEBUG - 2024-05-18 06:30:01 --> Nama: , Jumlah Layanan: 1, Total Harga Keseluruhan: 
ERROR - 2024-05-18 06:30:27 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:30:31 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:30:35 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:30:40 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:30:44 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:30:48 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:30:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:30:56 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:30:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:31:01 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:31:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:31:05 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:31:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:31:09 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:31:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 06:31:13 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-18 06:31:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
DEBUG - 2024-05-18 06:32:59 --> Nama: Tes, Alamat: Tess, No Telepon: 08111111
DEBUG - 2024-05-18 06:33:30 --> Nama: , Jumlah Layanan: 1, Total Harga Keseluruhan: 
INFO - 2024-05-18 07:27:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 07:28:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 08:01:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 08:01:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 08:02:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 08:02:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 08:04:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 08:20:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-18 08:40:25 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry: .jpg;"
[Method: GET, Route: user/images/laundry:%20.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry: .jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry: .jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 08:43:47 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry: .jpg;"
[Method: GET, Route: user/images/laundry:%20.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry: .jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry: .jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 08:47:22 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry: .jpg;"
[Method: GET, Route: user/images/laundry:%20.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry: .jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry: .jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 08:47:48 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry: .jpg;"
[Method: GET, Route: user/images/laundry:%20.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry: .jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry: .jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 08:49:32 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry: .jpg;"
[Method: GET, Route: user/images/laundry:%20.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry: .jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry: .jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 08:49:41 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry: .jpg;"
[Method: GET, Route: user/images/laundry:%20.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry: .jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry: .jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 08:50:01 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry: .jpg;"
[Method: GET, Route: user/images/laundry:%20.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry: .jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry: .jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 08:51:59 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "laundry.jpg;"
[Method: GET, Route: user/images/laundry.jpg;]
in SYSTEMPATH\Router\Router.php on line 736.
 1 SYSTEMPATH\Router\Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('user/images/laundry.jpg;')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('user/images/laundry.jpg;')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
INFO - 2024-05-18 11:27:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 11:48:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 12:01:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 12:02:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 12:02:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 13:16:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2024-05-18 13:17:15 --> Nama: ninis, Alamat: sukapura, No Telepon: 08111111
INFO - 2024-05-18 13:18:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-18 14:05:12 --> ParseError: Unclosed '{' on line 9
[Method: GET, Route: FormPemesananLayanan]
in APPPATH\Controllers\ValidationForm.php on line 43.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\tubes litdat\\ci4\\app\\Controllers\\ValidationForm.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ValidationForm')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ValidationForm')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\ValidationForm', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 14:11:04 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `fo...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-18 14:11:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: ValidationForm/processLayanan]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:11:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-24\', \'hanin\', NULL, \'2024-05-18 14:11:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-24\', \'hanin\', NULL, \'2024-05-18 14:11:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:11:04 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-24\', \'hanin\', NULL, \'2024-05-18 14:11:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-24\', \'hanin\', NULL, \'2024-05-18 14:11:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-24\', \'hanin\', NULL, \'2024-05-18 14:11:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 14:12:20 --> mysqli_sql_exception: Unknown table 'laundry.pelanggan' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('DROP TABLE `pel...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `pel...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `pel...')
#3 D:\tubes litdat\ci4\system\Database\Forge.php(663): CodeIgniter\Database\BaseConnection->query('DROP TABLE `pel...')
#4 D:\tubes litdat\ci4\app\Database\Migrations\2024-05-15-182844_FormPendaftaranPelanggan.php(38): CodeIgniter\Database\Forge->dropTable('pelanggan')
#5 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(867): App\Database\Migrations\FormPendaftaranPelanggan->down()
#6 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(290): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 D:\tubes litdat\ci4\system\Commands\Database\MigrateRollback.php(87): CodeIgniter\Database\MigrationRunner->regress(0)
#8 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 D:\tubes litdat\ci4\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 D:\tubes litdat\ci4\system\Commands\Database\MigrateRefresh.php(86): CodeIgniter\CLI\BaseCommand->call('migrate:rollbac...', Array)
#11 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 D:\tubes litdat\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 D:\tubes litdat\ci4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#14 D:\tubes litdat\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#15 D:\tubes litdat\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#16 {main}
ERROR - 2024-05-18 14:13:10 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `fo...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-18 14:13:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: ValidationForm/processLayanan]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:13:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-15\', \'2024-05-29\', \'sss\', \'2024-05-18 14:13:10\', \'2024-05-18 14:13:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-15\', \'2024-05-29\', \'sss\', \'2024-05-18 14:13:10\', \'2024-05-18 14:13:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:13:10 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-15\', \'2024-05-29\', \'sss\', \'2024-05-18 14:13:10\', \'2024-05-18 14:13:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-15\', \'2024-05-29\', \'sss\', \'2024-05-18 14:13:10\', \'2024-05-18 14:13:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-15\', \'2024-05-29\', \'sss\', \'2024-05-18 14:13:10\', \'2024-05-18 14:13:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ValidationForm.php(56): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 14:14:04 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `fo...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-18 14:14:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: ValidationForm/processLayanan]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:14:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:14:04\', \'2024-05-18 14:14:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:14:04\', \'2024-05-18 14:14:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:14:04 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:14:04\', \'2024-05-18 14:14:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:14:04\', \'2024-05-18 14:14:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:14:04\', \'2024-05-18 14:14:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 14:17:18 --> mysqli_sql_exception: Unknown table 'laundry.pelanggan' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('DROP TABLE `pel...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `pel...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `pel...')
#3 D:\tubes litdat\ci4\system\Database\Forge.php(663): CodeIgniter\Database\BaseConnection->query('DROP TABLE `pel...')
#4 D:\tubes litdat\ci4\app\Database\Migrations\2024-05-15-182844_FormPendaftaranPelanggan.php(38): CodeIgniter\Database\Forge->dropTable('pelanggan')
#5 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(867): App\Database\Migrations\FormPendaftaranPelanggan->down()
#6 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(290): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 D:\tubes litdat\ci4\system\Commands\Database\MigrateRollback.php(87): CodeIgniter\Database\MigrationRunner->regress(0)
#8 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 D:\tubes litdat\ci4\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 D:\tubes litdat\ci4\system\Commands\Database\MigrateRefresh.php(86): CodeIgniter\CLI\BaseCommand->call('migrate:rollbac...', Array)
#11 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 D:\tubes litdat\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 D:\tubes litdat\ci4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#14 D:\tubes litdat\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#15 D:\tubes litdat\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#16 {main}
ERROR - 2024-05-18 14:18:28 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `fo...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-18 14:18:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: ValidationForm/processLayanan]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:18:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:18:28\', \'2024-05-18 14:18:28\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:18:28\', \'2024-05-18 14:18:28\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:18:28 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:18:28\', \'2024-05-18 14:18:28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:18:28\', \'2024-05-18 14:18:28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-17\', \'2024-05-23\', \'mnmb\', \'2024-05-18 14:18:28\', \'2024-05-18 14:18:28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 14:18:58 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `fo...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-18 14:18:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: ValidationForm/processLayanan]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:18:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-29\', \'kddkmkd\', \'2024-05-18 14:18:58\', \'2024-05-18 14:18:58\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-29\', \'kddkmkd\', \'2024-05-18 14:18:58\', \'2024-05-18 14:18:58\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:18:58 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-29\', \'kddkmkd\', \'2024-05-18 14:18:58\', \'2024-05-18 14:18:58\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-29\', \'kddkmkd\', \'2024-05-18 14:18:58\', \'2024-05-18 14:18:58\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-29\', \'kddkmkd\', \'2024-05-18 14:18:58\', \'2024-05-18 14:18:58\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-18 14:27:01 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `fo...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-18 14:27:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: processLayanan]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:27:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-30\', \'ddd\', \'2024-05-18 14:27:01\', \'2024-05-18 14:27:01\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-30\', \'ddd\', \'2024-05-18 14:27:01\', \'2024-05-18 14:27:01\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 14:27:01 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-30\', \'ddd\', \'2024-05-18 14:27:01\', \'2024-05-18 14:27:01\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-30\', \'ddd\', \'2024-05-18 14:27:01\', \'2024-05-18 14:27:01\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (\'1\', NULL, NULL, NULL, \'2024-05-24\', \'2024-05-30\', \'ddd\', \'2024-05-18 14:27:01\', \'2024-05-18 14:27:01\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_layanan` (`jumlah_layanan`, `jenis_layanan`, `jumlah_kg`, `total_harga_perlayanan`, `tanggal_penyerahan`, `tanggal_pengambilan`, `catatan_tambahan`, `created_at`, `updated_at`) VALUES (:jumlah_layanan:, :jenis_layanan:, :jumlah_kg:, :total_harga_perlayanan:, :tanggal_penyerahan:, :tanggal_pengambilan:, :catatan_tambahan:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ValidationForm.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
INFO - 2024-05-18 14:37:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:37:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:38:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:39:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:40:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:40:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:40:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-18 14:41:13 --> mysqli_sql_exception: Unknown table 'laundry.pelanggan' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('DROP TABLE `pel...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `pel...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `pel...')
#3 D:\tubes litdat\ci4\system\Database\Forge.php(663): CodeIgniter\Database\BaseConnection->query('DROP TABLE `pel...')
#4 D:\tubes litdat\ci4\app\Database\Migrations\2024-05-15-182844_FormPendaftaranPelanggan.php(38): CodeIgniter\Database\Forge->dropTable('pelanggan')
#5 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(867): App\Database\Migrations\FormPendaftaranPelanggan->down()
#6 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(290): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 D:\tubes litdat\ci4\system\Commands\Database\MigrateRollback.php(87): CodeIgniter\Database\MigrationRunner->regress(0)
#8 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 D:\tubes litdat\ci4\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 D:\tubes litdat\ci4\system\Commands\Database\MigrateRefresh.php(86): CodeIgniter\CLI\BaseCommand->call('migrate:rollbac...', Array)
#11 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 D:\tubes litdat\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 D:\tubes litdat\ci4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#14 D:\tubes litdat\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#15 D:\tubes litdat\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#16 {main}
INFO - 2024-05-18 14:46:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2024-05-18 14:46:40 --> Nama: ita, Alamat: itu, No Telepon: ini
INFO - 2024-05-18 14:47:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:47:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 14:47:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-18 14:50:59 --> ParseError: Unclosed '{' on line 9
[Method: GET, Route: FormPemesananLayanan]
in APPPATH\Controllers\ValidationForm.php on line 57.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\tubes litdat\\ci4\\app\\Controllers\\ValidationForm.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ValidationForm')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ValidationForm')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\ValidationForm', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
INFO - 2024-05-18 14:51:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 15:04:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 15:05:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 15:05:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 15:06:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-18 15:09:08 --> ParseError: syntax error, unexpected token "else", expecting "function" or "const"
[Method: POST, Route: processLayanan]
in APPPATH\Controllers\ValidationForm.php on line 59.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\tubes litdat\\ci4\\app\\Controllers\\ValidationForm.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ValidationForm')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ValidationForm')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\ValidationForm', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-18 15:18:12 --> ErrorException: Undefined array key "nama"
[Method: POST, Route: processLayanan]
in APPPATH\Controllers\ValidationForm.php on line 29.
 1 APPPATH\Controllers\ValidationForm.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nama"', 'D:\\tubes litdat\\ci4\\app\\Controllers\\ValidationForm.php', 29)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
INFO - 2024-05-18 15:18:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-18 15:18:31 --> ErrorException: Undefined array key "nama"
[Method: POST, Route: processLayanan]
in APPPATH\Controllers\ValidationForm.php on line 29.
 1 APPPATH\Controllers\ValidationForm.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nama"', 'D:\\tubes litdat\\ci4\\app\\Controllers\\ValidationForm.php', 29)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ValidationForm->processLayanan()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ValidationForm))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
INFO - 2024-05-18 15:21:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-18 15:24:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
