ERROR - 2024-05-16 12:05:18 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:05:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 12:05:40 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:05:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 12:05:45 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:05:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 12:05:49 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:05:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 12:05:53 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:05:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 12:05:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:05:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 12:06:04 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:06:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 12:06:08 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'laundry', 3306, '', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\tubes litdat\ci4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 D:\tubes litdat\ci4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\tubes litdat\ci4\app\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
#7 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#13 {main}
CRITICAL - 2024-05-16 12:06:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: tables_dynamic.html]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `laporan_transaksi`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TableDynamics.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TableDynamics->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TableDynamics))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:05:10 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "form_advanced.php"
[Method: GET, Route: form_advanced.html]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form_advanced.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('form_advanced', [], true)
 3 APPPATH\Controllers\AdvancedForm.php(15): view('form_advanced')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:10:40 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "form_advanced.php"
[Method: GET, Route: form_advanced.html]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form_advanced.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('form_advanced', [], true)
 3 APPPATH\Controllers\AdvancedForm.php(15): view('form_advanced')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:10:41 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "form_advanced.php"
[Method: GET, Route: form_advanced.html]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form_advanced.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('form_advanced', [], true)
 3 APPPATH\Controllers\AdvancedForm.php(15): view('form_advanced')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:10:42 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "form_advanced.php"
[Method: GET, Route: form_advanced.html]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form_advanced.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('form_advanced', [], true)
 3 APPPATH\Controllers\AdvancedForm.php(15): view('form_advanced')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:10:43 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "form_advanced.php"
[Method: GET, Route: form_advanced.html]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form_advanced.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('form_advanced', [], true)
 3 APPPATH\Controllers\AdvancedForm.php(15): view('form_advanced')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:10:43 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "form_advanced.php"
[Method: GET, Route: form_advanced.html]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form_advanced.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('form_advanced', [], true)
 3 APPPATH\Controllers\AdvancedForm.php(15): view('form_advanced')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:10:47 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "form_advanced.php"
[Method: GET, Route: form_advanced.html]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form_advanced.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('form_advanced', [], true)
 3 APPPATH\Controllers\AdvancedForm.php(15): view('form_advanced')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 14:12:12 --> mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pe...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\AdvancedForm.php(35): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-16 14:12:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(35): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:12:12 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AdvancedForm.php(35): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:12:12 --> [Caused by] mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AdvancedForm.php(35): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 14:17:38 --> mysqli_sql_exception: Unknown table 'laundry.pelanggan' in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('DROP TABLE `pel...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `pel...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `pel...')
#3 D:\tubes litdat\ci4\system\Database\Forge.php(663): CodeIgniter\Database\BaseConnection->query('DROP TABLE `pel...')
#4 D:\tubes litdat\ci4\app\Database\Migrations\2024-05-15-182844_FormPendaftaranPelanggan.php(38): CodeIgniter\Database\Forge->dropTable('pelanggan')
#5 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(867): App\Database\Migrations\FormPendaftaranPelanggan->down()
#6 D:\tubes litdat\ci4\system\Database\MigrationRunner.php(290): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 D:\tubes litdat\ci4\system\Commands\Database\MigrateRollback.php(87): CodeIgniter\Database\MigrationRunner->regress(0)
#8 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 D:\tubes litdat\ci4\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 D:\tubes litdat\ci4\system\Commands\Database\MigrateRefresh.php(86): CodeIgniter\CLI\BaseCommand->call('migrate:rollbac...', Array)
#11 D:\tubes litdat\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 D:\tubes litdat\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 D:\tubes litdat\ci4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#14 D:\tubes litdat\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#15 D:\tubes litdat\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#16 {main}
ERROR - 2024-05-16 14:23:35 --> mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pe...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-16 14:23:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:23:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:23:35 --> [Caused by] mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
ERROR - 2024-05-16 14:28:07 --> mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pe...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-16 14:28:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:28:07 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:28:07 --> [Caused by] mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:36:16 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 913.
 1 SYSTEMPATH\Model.php(705): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(350): CodeIgniter\Model->builder()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:38:29 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 913.
 1 SYSTEMPATH\Model.php(705): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(350): CodeIgniter\Model->builder()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(28): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
DEBUG - 2024-05-16 14:46:36 --> Nama: hanin, Alamat: sukapura, No Telepon: 08111111
ERROR - 2024-05-16 14:46:36 --> mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pe...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-16 14:46:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:46:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:46:36 --> [Caused by] mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
DEBUG - 2024-05-16 14:47:22 --> Nama: hanin, Alamat: sukapura, No Telepon: 08111111
ERROR - 2024-05-16 14:47:22 --> mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pe...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-16 14:47:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:47:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:47:22 --> [Caused by] mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
DEBUG - 2024-05-16 14:48:55 --> Nama: hanin, Alamat: sukapura, No Telepon: 08111111
ERROR - 2024-05-16 14:48:55 --> mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pe...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-16 14:48:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:48:55 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 14:48:55 --> [Caused by] mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
DEBUG - 2024-05-16 15:31:47 --> Nama: hanin, Alamat: sukapura, No Telepon: 08111111
ERROR - 2024-05-16 15:31:47 --> mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist in D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 D:\tubes litdat\ci4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pe...', 0)
#1 D:\tubes litdat\ci4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 D:\tubes litdat\ci4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 D:\tubes litdat\ci4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 D:\tubes litdat\ci4\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\tubes litdat\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\tubes litdat\ci4\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\tubes litdat\ci4\app\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert(Array)
#8 D:\tubes litdat\ci4\system\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
#9 D:\tubes litdat\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
#10 D:\tubes litdat\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\tubes litdat\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 D:\tubes litdat\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\tubes litdat\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\tubes litdat\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat...')
#15 {main}
CRITICAL - 2024-05-16 15:31:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
[Method: POST, Route: AdvancedForm/processForm]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 15:31:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
CRITICAL - 2024-05-16 15:31:47 --> [Caused by] mysqli_sql_exception: Table 'laundry.pelanggan' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (\'hanin\', \'sukapura\', \'08111111\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pelanggan` (`nama`, `alamat`, `no_telepon`) VALUES (:nama:, :alamat:, :no_telepon:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AdvancedForm.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdvancedForm->processForm()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdvancedForm))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\tubes litdat\\ci4\\public\\index.php')
DEBUG - 2024-05-16 15:36:14 --> Nama: hanin, Alamat: sukapura, No Telepon: 08111111
DEBUG - 2024-05-16 15:39:13 --> Nama: hanin, Alamat: sukapura, No Telepon: 08111111
DEBUG - 2024-05-16 16:23:27 --> Nama: , Jumlah Layanan: 1, Total Harga Keseluruhan: , Tanggal Penyerahan: 2024-05-09, Tanggal Pengambilan: 2024-05-14, Catatan Tambahan: , Status Pembayaran: , Status Pengambilan: 
DEBUG - 2024-05-16 16:25:39 --> Nama: , Jumlah Layanan: 1, Total Harga Keseluruhan: , Tanggal Penyerahan: 2024-05-23, Tanggal Pengambilan: 2024-05-24, Catatan Tambahan: , Status Pembayaran: , Status Pengambilan: 
